"""empty message

Revision ID: 0f25a5e5b7a0
Revises: 2a061003242a
Create Date: 2022-06-05 02:38:04.771542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f25a5e5b7a0'
down_revision = '2a061003242a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('seeking_description', sa.String(), nullable=True))
    op.drop_column('artists', 'venue_description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('venue_description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('artists', 'seeking_description')
    # ### end Alembic commands ###
